=== marcvifi10/Curso-Access/2. Access 2010 Avanzado/2 - Exportación/7 - Exportación II Vídeo 7/ALUMNO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="ALUMNO" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="ALUMNO">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="DNI " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADgnttbapc+SYt5NEWp6TeAAAAAAAuqDG42SOVAAAAAAAAAAABBAEwA
VQBNAE4ATwAAAAAAAAC3uhBsflbvTrxYIGaKhRWiBwAAAOCe21tqlz5Ji3k0Ranp
N4BEAE4ASQAAAAAAAAAEOMDJn21GTISNrIOgoUT9BwAAAOCe21tqlz5Ji3k0Ranp
N4BOAE8ATQBCAFIARQAAAAAAAAArf2RyKtRSSb3G/Kuv1iuFBwAAAOCe21tqlz5J
i3k0RanpN4BBAFAARQBMAEwASQBEAE8AUwAAAAAAAADlrAxxFZ5SSrgGKzmu4vOy
BwAAAOCe21tqlz5Ji3k0RanpN4BQAE8AQgBMAEEAQwBJANMATgAAAAAAAADEY87D
zhAaTJ+TJiBNp0+iBwAAAOCe21tqlz5Ji3k0RanpN4BGAEUAQwBIAEEAIABEAEUA
IABOAEEAQwBJAE0ASQBFAE4AVABPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAA
BQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="4J7bW2qXPkmLeTRFqek3gA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="DNI" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="InputMask" type="10" value="00000000\-L"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="t7oQbH5W7068WCBmioUVog==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NOMBRE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="BDjAyZ9tRkyEjayDoKFE/Q==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="APELLIDOS" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2160"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="K39kcirUUkm9xvyrr9YrhQ==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="POBLACIÃ“N" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2925"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="5awMcRWeUkq4Bis5ruLzsg==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="FECHA_x0020_DE_x0020_NACIMIENTO" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1890"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="xGPOw84QGkyfkyYgTadPog==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== marcvifi10/Curso-Access/2. Access 2010 Avanzado/2 - Exportación/7 - Exportación II Vídeo 7/ALUMNO.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="ALUMNO.xsd" generated="2019-05-01T16:01:35">
<ALUMNO>
<DNI>04050022R</DNI>
<NOMBRE>MANUEL</NOMBRE>
<APELLIDOS>ROCA CARRASCO</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1980-03-03T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>05254558J</DNI>
<NOMBRE>MARÍA</NOMBRE>
<APELLIDOS>MARTIN</APELLIDOS>
<POBLACIÓN>TOLEDO</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1965-02-12T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>05874422H</DNI>
<NOMBRE>MATÍAS</NOMBRE>
<APELLIDOS>ADÁN PÉREZ</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1970-02-08T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>05874555H</DNI>
<NOMBRE>PEDRO</NOMBRE>
<APELLIDOS>CALLE HERNÁN</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1978-02-10T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>05875633H</DNI>
<NOMBRE>MARISA</NOMBRE>
<APELLIDOS>DE LA FUENTE VILLA</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1970-05-05T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>06874226D</DNI>
<NOMBRE>FERNANDO</NOMBRE>
<APELLIDOS>MARTIN ROJAS</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1975-02-02T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>21542365L</DNI>
<NOMBRE>JUAN</NOMBRE>
<APELLIDOS>RODA VILLA</APELLIDOS>
<POBLACIÓN>ARAVACA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1970-02-21T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>22325501J</DNI>
<NOMBRE>JUAN</NOMBRE>
<APELLIDOS>BLANCO LÓPEZ</APELLIDOS>
<POBLACIÓN>ALCOBENDAS</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1975-02-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>25874123L</DNI>
<NOMBRE>LOURDES</NOMBRE>
<APELLIDOS>VILLA MARTIN</APELLIDOS>
<POBLACIÓN>GETAFE</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1970-02-21T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>31254878H</DNI>
<NOMBRE>CARMEN</NOMBRE>
<APELLIDOS>MUÑOZ LILLO</APELLIDOS>
<POBLACIÓN>FUENLABRADA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1963-04-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>34875522F</DNI>
<NOMBRE>MARCOS</NOMBRE>
<APELLIDOS>BLANCO ROJAS</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1966-02-02T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35785554L</DNI>
<NOMBRE>RICARDO</NOMBRE>
<APELLIDOS>MEDINA MEDINA</APELLIDOS>
<POBLACIÓN>MÓSTOLES</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1971-05-03T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35821455T</DNI>
<NOMBRE>PEDRO</NOMBRE>
<APELLIDOS>RAMÍREZ GALLEGO</APELLIDOS>
<POBLACIÓN>GETAFE</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1970-05-26T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35847122S</DNI>
<NOMBRE>MARÍA</NOMBRE>
<APELLIDOS>RUIZ PÉREZ</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1956-05-21T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35863332R</DNI>
<NOMBRE>RAQUEL</NOMBRE>
<APELLIDOS>MARTIN PERAL</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1975-07-07T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35874225L</DNI>
<NOMBRE>ANTONIO</NOMBRE>
<APELLIDOS>SUÁREZ BLANCO</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1969-08-21T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35874586T</DNI>
<NOMBRE>JUAN</NOMBRE>
<APELLIDOS>CALLE LÓPEZ</APELLIDOS>
<POBLACIÓN>VILLALBA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1974-05-15T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35896654E</DNI>
<NOMBRE>CARLOS</NOMBRE>
<APELLIDOS>MORA CRESPO</APELLIDOS>
<POBLACIÓN>VILLALBA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1968-05-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>35996887P</DNI>
<NOMBRE>ANTONIO</NOMBRE>
<APELLIDOS>MARTIN RECUERO</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1959-04-15T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>36358741P</DNI>
<NOMBRE>LORENZO</NOMBRE>
<APELLIDOS>PÉREZ BLANCO</APELLIDOS>
<POBLACIÓN>FUENLABRADA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1966-05-26T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>36587493G</DNI>
<NOMBRE>ANTONIO</NOMBRE>
<APELLIDOS>MEDINA LÓPEZ</APELLIDOS>
<POBLACIÓN>VILLANUEVA DE LA CAÑADA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1974-06-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>36874225G</DNI>
<NOMBRE>BENITO</NOMBRE>
<APELLIDOS>PÉREZ MEDINA</APELLIDOS>
<POBLACIÓN>POZUELO</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1961-04-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>37855222J</DNI>
<NOMBRE>ROSA</NOMBRE>
<APELLIDOS>LÓPEZ LILLO</APELLIDOS>
<POBLACIÓN>PARLA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1974-02-02T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>38745855J</DNI>
<NOMBRE>MARÍA</NOMBRE>
<APELLIDOS>SÁNCHEZ LILLO</APELLIDOS>
<POBLACIÓN>FUENLABRADA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1966-04-15T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>38954777J</DNI>
<NOMBRE>MARTA</NOMBRE>
<APELLIDOS>LÓPEZ MARTIN</APELLIDOS>
<POBLACIÓN>GETAFE</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1988-05-15T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>38955477R</DNI>
<NOMBRE>Mª ÁNGELES</NOMBRE>
<APELLIDOS>LILLO MARTIN</APELLIDOS>
<POBLACIÓN>PARLA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1964-04-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>38957236D</DNI>
<NOMBRE>Mª JOSÉ</NOMBRE>
<APELLIDOS>MARTIN VILLANUEVA</APELLIDOS>
<POBLACIÓN>PARLA</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1970-05-25T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>39718254S</DNI>
<NOMBRE>HÉCTOR</NOMBRE>
<APELLIDOS>MARTIN JIMÉNEZ</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1965-07-07T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
<ALUMNO>
<DNI>39854885H</DNI>
<NOMBRE>CELIA</NOMBRE>
<APELLIDOS>DÍAZ RECUERO</APELLIDOS>
<POBLACIÓN>MADRID</POBLACIÓN>
<FECHA_x0020_DE_x0020_NACIMIENTO>1964-07-10T00:00:00</FECHA_x0020_DE_x0020_NACIMIENTO>
</ALUMNO>
</dataroot>
